In [19]:
import numpy as np
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [21]:
b = np.zeros(2)
b

array([0., 0.])

In [23]:
c = np.ones(3)
c

array([1., 1., 1.])

In [25]:
# Create an empty array with 2 elements
d = np.empty(3)
d

array([1., 1., 1.])

# How to create an array ?

In [28]:
# with range of elements 
e = np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [30]:
# with specific range of elements
f = np.arange(2,20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [32]:
# continue...
g = np.arange(2,20,2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
# linerly spaced arrays
h = np.linspace(0,10,num=5) # gives use 5 nums
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
# spceific data types in array 
i = np.ones(5,dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [38]:
j = np.ones(3,dtype=np.float64)
j

array([1., 1., 1.])

# How to create an array ? 
##  2-D arrays

In [48]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
np.ones( (5,6) )

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [52]:
np.empty( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# How to create an array ?
## 3-D array

In [57]:
# making and reshpaing a 3D array 
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])