# numpy pratice session

In [3]:
import numpy as np

# creating an array using numpy


In [5]:
# 1-D array
food = np.array(["Pakora","Samosa","Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [7]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [9]:
type(price)

numpy.ndarray

In [11]:
type(food)


numpy.ndarray

In [13]:
len(food)

3

In [15]:
price[0:]

array([5, 5, 5])

In [19]:
food[2]

'Raita'

In [21]:
price.mean()

5.0

In [23]:
# zeros 
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [25]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
# empty 
np.empty(5)

array([1., 1., 1., 1., 1.])

In [29]:
# arange
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# specify 
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [33]:
# specify interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
# table of 5
np.arange(5,55,5)


array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [39]:
# line space 
np.linspace(1,100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [45]:
# specify your data type
np.ones(50, dtype =np.int64)


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [47]:
np.ones(50, dtype =np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array functions

In [50]:
a = np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [54]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [56]:
b = np.array([12.4,39.3,45.2,22.3,44.3])
b

array([12.4, 39.3, 45.2, 22.3, 44.3])

In [58]:
c = np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  12.4,  39.3,  45.2,  22.3,  44.3])

In [60]:
c.sort()
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  12.4,  15. ,
        22.3,  39.3,  44.3,  45.2, 100. , 320. ])

# 2-D arrays

In [73]:
a = np.array([[1,2], [5,4]])
a

array([[1, 2],
       [5, 4]])

In [69]:
b = np.array([[6,7],[7,8]])
b

array([[6, 7],
       [7, 8]])

In [77]:
c = np.concatenate((a,b), axis=0)
c

array([[1, 2],
       [5, 4],
       [6, 7],
       [7, 8]])

In [79]:
np.concatenate((a,b), axis=1)

array([[1, 2, 6, 7],
       [5, 4, 7, 8]])

In [81]:
#to din the number of dimenstions
a.ndim

2

In [91]:
type(a)

numpy.ndarray

In [87]:
b =np.array([[5,6,7],
           [8,9,10],
           [10,11,12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [89]:
b.ndim

2

In [95]:
# size(number of elements)
a.size

4

In [97]:
# shape 
a.shape

(2, 2)

In [103]:
a = np.arange(9) # 3*3 =9
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [105]:
a = a.reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [107]:
# reshape 
np.reshape(a, newshape=(1,9), order= 'c')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [109]:
# convert 1D into 2D
a =np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
a.shape

(9,)

In [113]:
# row wise 2D
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [115]:
b.shape

(1, 9)

In [117]:
# column wise
c = a[: , np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [119]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
a[2:6]

array([3, 4, 5, 6])

In [123]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [125]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [127]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [129]:
a.sum()

45

In [131]:
a.mean()

5.0